from typing import List, Annotated, Literal
from pydantic import BaseModel, Field

class ChatMessage(BaseModel):
    role: Annotated[
        Literal["user", "assistant"], 
        Field(..., description = "role of the message sender (user or assistant)")
        ]
    
    content: Annotated[
        str,
        Field(..., description = "message sent by the sender")
    ]

class RagFilters(BaseModel):
    semester: Annotated[
        int,
        Field(..., ge = 1, le = 8, description = "Semester number", examples = [1, 2])
    ]
    
    subject: Annotated[
        str,
        Field(..., description = "subject name", examples = ["aoa", "os"])
    ]
    
    unit: Annotated[
        int,
        Field(..., ge = 1, le = 7, description = "unit number of the subject", examples = [1, 2])
    ]

class RagQueryRequest(BaseModel):
    query: Annotated[
        str,
        Field(..., description = "User's latest question", examples = ["What is an algorithm?"])
    ]
    
    chat_history: Annotated[
        List[ChatMessage],
        Field(..., description = "Previous conversation turns")
    ]
    
    filters: Annotated[
        RagFilters,
        Field(..., description = "Metadata filters for retrieval")
    ]

class RagQueryResponse(BaseModel):
    answer: Annotated[
        str,
        Field(..., description = "Final answer generated by the RAG system")
    ]
    
    rewritten_query: Annotated[
        str,
        Field(..., description = "Rewritten self-contained query")
    ]